oov_words = ['alarm clock', 'ceiling fan', 'tail fin', 'birthday cake', 'stop sign,stopsign', 'microwave,'
                                                                                              'microwave oven',
             'skateboard ramp', 'refrigerator,fridge', 'knee pads', 'tennis court', 'tea pot', 'television,tv',
             'garage door', 'sailboat,sail boat', 'racket,racquet', 'rock wall', 'headboard,head board',
             'tea kettle', 'tennis racket,tennis racquet', 'train station', 'tennis player', 'toilet brush',
             'pepper shaker', 'hair dryer', 'toilet seat', 'skateboard,skate board', 'floor lamp',
             'french fries', 'christmas tree', 'living room', 'teddy bear', 'baseball field', 'ski boot',
             'shower curtain', 'polar bear', 'hot dog,hotdog', 'surfboard,surf board', 'dirt bike', 'tail wing',
             'area rug', 'bow tie', 'fire extinguisher', 'tail feathers', 'beach chair', 'fire hydrant,hydrant',
             'weather vane', 'soccer ball', 'head band', 'bath tub', 'coffee table', 'traffic light',
             'parking meter', 'wet suit', 'teddy bears', 'suitcase,suit case', 'tank top', 'shin guard',
             'wii remote', 'pizza slice', 'home plate', 'ski boots', 'snow suit', 'banana slice',
             'stuffed animals', 'train platform', 'tissue box', 'cutting board', 'license plate', 'ski pole',
             'clock tower', 'toilet tank', 'palm trees', 'skate park', 'computer monitor', 'flip flop',
             'remote control', 'paper towels', 'train tracks', 'donut,doughnut', 'soccer player', 'toilet bowl',
             'lounge chair', 'sidewalk,side walk', 'stove top,stovetop', 'tomato slice', 'window sill',
             'toilet lid', "pitcher's mound", 'palm tree', 'banana bunch', 'tennis shoe', 'giraffe head',
             'baseball player', 'water bottle', 'tennis ball', 'cell phone', 'computer mouse', 'ski pants',
             'clock face', 'fire escape', 'police officer', 'trash can', 'front window', 'office chair',
             'door knob', 'banana peel', 'baseball game', 'cabinet door', 'traffic cone', 'nightstand,'
                                                                                          'night stand',
             'suit jacket', 'train engine', 'wrist band', 'toilet paper', 'street sign', 'computer screen',
             'wine glass', 'train car', 'donuts,doughnuts', 'tennis match', 'railroad tracks', 'stuffed bear',
             'snow pants', 'neck tie', 'baseball bat', 'safety cone', 'paper towel', 'back wheel',
             'soccer field', 'throw pillow', 'oven door', 'lamp shade', 'pine tree', 'lamp post,lamppost',
             'station wagon', 'signal light', 'american flag', 'baseball cap', 'front legs', 'life jacket',
             'water tank', 'gas station', 'entertainment center', 'stuffed animal', 'display case',
             'front wheel', 'coffee pot', 'cowboy hat', 'table cloth', 'fire truck,firetruck', 'game controller',
             'sweat band', 'coin slot', 'pillow case', 'coffee cup', 'counter top', 'baseball uniform',
             'book shelf', 'facial hair', 'end table', 'shin guards', 'head light', 'tennis net', 'trash bag',
             'ski poles', 'parking lot', 'gas tank', 'soap dispenser', 'life vest', 'train front',
             'exhaust pipe', 'light fixture', 'power lines', 'roman numerals', 'picnic table', 'wine bottle',
             'tree trunk', 'motor bike', 'traffic sign', 'little girl', 'passenger car', 'brake light',
             'roman numeral', 'shower head', 'handle bars', 'cardboard box', 'mountain range', 'eye glasses',
             'salt shaker', 'knee pad', 'shower door', 'bathing suit', 'manhole cover', 'door handle',
             'picture frame', 'hour hand', 'dvd player', 'ski slope', 'french fry', 'landing gear',
             'coffee maker', 'light switch', 'tv stand', 'air vent', 'steering wheel', 'baseball glove',
             'power pole', 'dirt road', 'telephone pole', 'jet engine', 'tee shirt', 'face mask',
             'bathroom sink', 'laptop computer', 'windshield wipers', 'hill side', 'tail light,taillight',
             'snow board', 'stop light', 'ball cap', 'traffic signal', 'soda can', 'ski lift', 'tennis shoes',
             'swim trunks', 'butter knife', 'train cars', 'pine trees', 'park bench', 'second floor',
             'hand towel', 'flip flops', 'back pack', 'ski tracks', 'baseball players', 'stone wall',
             'dress shirt', 'ski goggles', 'power line', 'train track', 'air conditioner', 'baseball mitt',
             'mouse pad', 'garbage can', 'taxi cab', 'control panel', 'clock hand', 'brick wall', 'grass field',
             'utility pole', 'mountain top', 'hot dogs,hotdogs', 'bed frame', 'tail lights', 'traffic lights',
             'candle holder', 'guard rail', 'tree branches', 'trash bin', 'side mirror', 'light pole',
             'street lamp', 'paper plate', 'fence post', 'door frame', 'tshirt,t-shirt,t shirt', 'wire fence',
             'side window', 'table lamp', 'pony tail', 'ocean water', 'flower pot', 'tree line', 'sign post',
             'ski suit', 'passenger train', "catcher's mitt", 'electrical outlet', 'bike rack', 'windshield '
                                                                                                'wiper',
             'bus stop', 'police car', 'name tag', 'computer keyboard', 'glass door', 'wine glasses',
             'young man', 'light post', 'ski jacket', 'streetlight,street light', 'beer bottle', 'wrist watch',
             'tile floor', 'tree branch', 'towel rack']
